version: "3.9"

x-base-service: &base-service
  build:
    context: .
    dockerfile: docker/production.Dockerfile
  environment:
    - DATABASE_URL=psql://tta:tta123@db-production:5432/tracktraceapi
    - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq-production:5672//
  volumes:
    - .:/app
  depends_on:
    - db-production
    - rabbitmq-production
  restart: on-failure

services:
  db-production:
    image: postgres:14.1
    container_name: db-production
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=tracktraceapi
      - POSTGRES_USER=tta
      - POSTGRES_PASSWORD=tta123

  rabbitmq-production:
    image: rabbitmq:alpine
    container_name: rabbitmq-production
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  django-production:
    <<: *base-service
    container_name: django-production
    command: ./docker/web_entrypoint.sh
    ports:
      - "8003:8000"

  celery-production:
    <<: *base-service
    container_name: worker-production
    command: ./docker/celery_entrypoint.sh

  beats-production:
    <<: *base-service
    container_name: beats-production
    command: ./docker/beats_entrypoint.sh
    